
namespace K_PlateOnAngleBeam
{
    partial class FormBolt
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormBolt));
            this.ch_checkw1 = new System.Windows.Forms.CheckBox();
            this.ch_checkw3 = new System.Windows.Forms.CheckBox();
            this.ch_checkw2 = new System.Windows.Forms.CheckBox();
            this.ch_checkn1 = new System.Windows.Forms.CheckBox();
            this.ch_checkn2 = new System.Windows.Forms.CheckBox();
            this.ch_checkb = new System.Windows.Forms.CheckBox();
            this.label17 = new System.Windows.Forms.Label();
            this.txt_Bolt_tole = new System.Windows.Forms.TextBox();
            this.boltCatalogSize1 = new Tekla.Structures.Dialog.UIControls.BoltCatalogSize();
            this.txt_Bolt_extra = new System.Windows.Forms.TextBox();
            this.boltCatalogStandard1 = new Tekla.Structures.Dialog.UIControls.BoltCatalogStandard();
            this.imageListComboBox2 = new Tekla.Structures.Dialog.UIControls.ImageListComboBox();
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.label11 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.pictureBox10 = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox10)).BeginInit();
            this.SuspendLayout();
            // 
            // ch_checkw1
            // 
            this.structuresExtender.SetAttributeName(this.ch_checkw1, null);
            this.structuresExtender.SetAttributeTypeName(this.ch_checkw1, null);
            this.ch_checkw1.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.ch_checkw1, null);
            this.ch_checkw1.Location = new System.Drawing.Point(184, 169);
            this.ch_checkw1.Margin = new System.Windows.Forms.Padding(4);
            this.ch_checkw1.Name = "ch_checkw1";
            this.ch_checkw1.Size = new System.Drawing.Size(79, 21);
            this.ch_checkw1.TabIndex = 91;
            this.ch_checkw1.Text = "Washer";
            this.ch_checkw1.UseVisualStyleBackColor = true;
            // 
            // ch_checkw3
            // 
            this.structuresExtender.SetAttributeName(this.ch_checkw3, null);
            this.structuresExtender.SetAttributeTypeName(this.ch_checkw3, null);
            this.ch_checkw3.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.ch_checkw3, null);
            this.ch_checkw3.Location = new System.Drawing.Point(184, 242);
            this.ch_checkw3.Margin = new System.Windows.Forms.Padding(4);
            this.ch_checkw3.Name = "ch_checkw3";
            this.ch_checkw3.Size = new System.Drawing.Size(79, 21);
            this.ch_checkw3.TabIndex = 90;
            this.ch_checkw3.Text = "Washer";
            this.ch_checkw3.UseVisualStyleBackColor = true;
            // 
            // ch_checkw2
            // 
            this.structuresExtender.SetAttributeName(this.ch_checkw2, null);
            this.structuresExtender.SetAttributeTypeName(this.ch_checkw2, null);
            this.ch_checkw2.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.ch_checkw2, null);
            this.ch_checkw2.Checked = true;
            this.ch_checkw2.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ch_checkw2.Location = new System.Drawing.Point(184, 216);
            this.ch_checkw2.Margin = new System.Windows.Forms.Padding(4);
            this.ch_checkw2.Name = "ch_checkw2";
            this.ch_checkw2.Size = new System.Drawing.Size(79, 21);
            this.ch_checkw2.TabIndex = 89;
            this.ch_checkw2.Text = "Washer";
            this.ch_checkw2.UseVisualStyleBackColor = true;
            // 
            // ch_checkn1
            // 
            this.structuresExtender.SetAttributeName(this.ch_checkn1, null);
            this.structuresExtender.SetAttributeTypeName(this.ch_checkn1, null);
            this.ch_checkn1.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.ch_checkn1, null);
            this.ch_checkn1.Checked = true;
            this.ch_checkn1.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ch_checkn1.Location = new System.Drawing.Point(184, 266);
            this.ch_checkn1.Margin = new System.Windows.Forms.Padding(4);
            this.ch_checkn1.Name = "ch_checkn1";
            this.ch_checkn1.Size = new System.Drawing.Size(52, 21);
            this.ch_checkn1.TabIndex = 88;
            this.ch_checkn1.Text = "Nut";
            this.ch_checkn1.UseVisualStyleBackColor = true;
            // 
            // ch_checkn2
            // 
            this.structuresExtender.SetAttributeName(this.ch_checkn2, null);
            this.structuresExtender.SetAttributeTypeName(this.ch_checkn2, null);
            this.ch_checkn2.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.ch_checkn2, null);
            this.ch_checkn2.Checked = true;
            this.ch_checkn2.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ch_checkn2.Location = new System.Drawing.Point(184, 292);
            this.ch_checkn2.Margin = new System.Windows.Forms.Padding(4);
            this.ch_checkn2.Name = "ch_checkn2";
            this.ch_checkn2.Size = new System.Drawing.Size(52, 21);
            this.ch_checkn2.TabIndex = 87;
            this.ch_checkn2.Text = "Nut";
            this.ch_checkn2.UseVisualStyleBackColor = true;
            // 
            // ch_checkb
            // 
            this.structuresExtender.SetAttributeName(this.ch_checkb, null);
            this.structuresExtender.SetAttributeTypeName(this.ch_checkb, null);
            this.ch_checkb.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.ch_checkb, null);
            this.ch_checkb.Checked = true;
            this.ch_checkb.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ch_checkb.Location = new System.Drawing.Point(184, 144);
            this.ch_checkb.Margin = new System.Windows.Forms.Padding(4);
            this.ch_checkb.Name = "ch_checkb";
            this.ch_checkb.Size = new System.Drawing.Size(54, 21);
            this.ch_checkb.TabIndex = 86;
            this.ch_checkb.Text = "Bolt";
            this.ch_checkb.UseVisualStyleBackColor = true;
            // 
            // label17
            // 
            this.structuresExtender.SetAttributeName(this.label17, null);
            this.structuresExtender.SetAttributeTypeName(this.label17, null);
            this.label17.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.label17, null);
            this.label17.Location = new System.Drawing.Point(24, 100);
            this.label17.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(72, 17);
            this.label17.TabIndex = 82;
            this.label17.Text = "Tolerance";
            // 
            // txt_Bolt_tole
            // 
            this.structuresExtender.SetAttributeName(this.txt_Bolt_tole, null);
            this.structuresExtender.SetAttributeTypeName(this.txt_Bolt_tole, null);
            this.structuresExtender.SetBindPropertyName(this.txt_Bolt_tole, null);
            this.txt_Bolt_tole.Location = new System.Drawing.Point(139, 96);
            this.txt_Bolt_tole.Margin = new System.Windows.Forms.Padding(4);
            this.txt_Bolt_tole.Name = "txt_Bolt_tole";
            this.txt_Bolt_tole.Size = new System.Drawing.Size(160, 22);
            this.txt_Bolt_tole.TabIndex = 85;
            // 
            // boltCatalogSize1
            // 
            this.structuresExtender.SetAttributeName(this.boltCatalogSize1, null);
            this.structuresExtender.SetAttributeTypeName(this.boltCatalogSize1, null);
            this.structuresExtender.SetBindPropertyName(this.boltCatalogSize1, null);
            this.boltCatalogSize1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.boltCatalogSize1.FormattingEnabled = true;
            this.boltCatalogSize1.Location = new System.Drawing.Point(139, 63);
            this.boltCatalogSize1.Margin = new System.Windows.Forms.Padding(4);
            this.boltCatalogSize1.Name = "boltCatalogSize1";
            this.boltCatalogSize1.Size = new System.Drawing.Size(160, 24);
            this.boltCatalogSize1.TabIndex = 83;
            // 
            // txt_Bolt_extra
            // 
            this.structuresExtender.SetAttributeName(this.txt_Bolt_extra, null);
            this.structuresExtender.SetAttributeTypeName(this.txt_Bolt_extra, null);
            this.structuresExtender.SetBindPropertyName(this.txt_Bolt_extra, null);
            this.txt_Bolt_extra.Location = new System.Drawing.Point(51, 318);
            this.txt_Bolt_extra.Margin = new System.Windows.Forms.Padding(4);
            this.txt_Bolt_extra.Name = "txt_Bolt_extra";
            this.txt_Bolt_extra.Size = new System.Drawing.Size(96, 22);
            this.txt_Bolt_extra.TabIndex = 84;
            // 
            // boltCatalogStandard1
            // 
            this.structuresExtender.SetAttributeName(this.boltCatalogStandard1, "bangma");
            this.structuresExtender.SetAttributeTypeName(this.boltCatalogStandard1, "String");
            this.structuresExtender.SetBindPropertyName(this.boltCatalogStandard1, null);
            this.boltCatalogStandard1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.boltCatalogStandard1.FormattingEnabled = true;
            this.boltCatalogStandard1.LinkedBoltCatalogSize = this.boltCatalogSize1;
            this.boltCatalogStandard1.Location = new System.Drawing.Point(139, 26);
            this.boltCatalogStandard1.Margin = new System.Windows.Forms.Padding(4);
            this.boltCatalogStandard1.Name = "boltCatalogStandard1";
            this.boltCatalogStandard1.Size = new System.Drawing.Size(160, 24);
            this.boltCatalogStandard1.TabIndex = 77;
            // 
            // imageListComboBox2
            // 
            this.structuresExtender.SetAttributeName(this.imageListComboBox2, null);
            this.structuresExtender.SetAttributeTypeName(this.imageListComboBox2, null);
            this.imageListComboBox2.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.imageListComboBox2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(241)))), ((int)(((byte)(241)))));
            this.imageListComboBox2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.structuresExtender.SetBindPropertyName(this.imageListComboBox2, null);
            this.imageListComboBox2.DefaultValue = "";
            this.imageListComboBox2.HoverColor = System.Drawing.Color.DodgerBlue;
            this.imageListComboBox2.ImageList = this.imageList1;
            this.imageListComboBox2.Location = new System.Drawing.Point(329, 30);
            this.imageListComboBox2.Margin = new System.Windows.Forms.Padding(4);
            this.imageListComboBox2.MaximumSize = new System.Drawing.Size(6667, 6154);
            this.imageListComboBox2.MinimumSize = new System.Drawing.Size(100, 86);
            this.imageListComboBox2.Name = "imageListComboBox2";
            this.imageListComboBox2.SelectedIndex = -1;
            this.imageListComboBox2.SelectedItem = null;
            this.imageListComboBox2.Size = new System.Drawing.Size(100, 86);
            this.imageListComboBox2.TabIndex = 81;
            this.imageListComboBox2.ToolTipText = "";
            // 
            // imageList1
            // 
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "BoltRotate1 - Copy.png");
            this.imageList1.Images.SetKeyName(1, "BoltRotate1.png");
            // 
            // label11
            // 
            this.structuresExtender.SetAttributeName(this.label11, null);
            this.structuresExtender.SetAttributeTypeName(this.label11, null);
            this.label11.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.label11, null);
            this.label11.Location = new System.Drawing.Point(24, 30);
            this.label11.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(92, 17);
            this.label11.TabIndex = 78;
            this.label11.Text = "Bolt standard";
            // 
            // label15
            // 
            this.structuresExtender.SetAttributeName(this.label15, null);
            this.structuresExtender.SetAttributeTypeName(this.label15, null);
            this.label15.AutoSize = true;
            this.structuresExtender.SetBindPropertyName(this.label15, null);
            this.label15.Location = new System.Drawing.Point(24, 63);
            this.label15.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(61, 17);
            this.label15.TabIndex = 79;
            this.label15.Text = "Bolt size";
            // 
            // pictureBox10
            // 
            this.structuresExtender.SetAttributeName(this.pictureBox10, null);
            this.structuresExtender.SetAttributeTypeName(this.pictureBox10, null);
            this.structuresExtender.SetBindPropertyName(this.pictureBox10, null);
            this.pictureBox10.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox10.Image")));
            this.pictureBox10.Location = new System.Drawing.Point(28, 140);
            this.pictureBox10.Margin = new System.Windows.Forms.Padding(4);
            this.pictureBox10.Name = "pictureBox10";
            this.pictureBox10.Size = new System.Drawing.Size(230, 173);
            this.pictureBox10.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pictureBox10.TabIndex = 80;
            this.pictureBox10.TabStop = false;
            // 
            // FormBolt
            // 
            this.structuresExtender.SetAttributeName(this, null);
            this.structuresExtender.SetAttributeTypeName(this, null);
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.structuresExtender.SetBindPropertyName(this, null);
            this.ClientSize = new System.Drawing.Size(444, 394);
            this.Controls.Add(this.ch_checkw1);
            this.Controls.Add(this.ch_checkw3);
            this.Controls.Add(this.ch_checkw2);
            this.Controls.Add(this.ch_checkn1);
            this.Controls.Add(this.ch_checkn2);
            this.Controls.Add(this.ch_checkb);
            this.Controls.Add(this.label17);
            this.Controls.Add(this.txt_Bolt_tole);
            this.Controls.Add(this.boltCatalogSize1);
            this.Controls.Add(this.txt_Bolt_extra);
            this.Controls.Add(this.boltCatalogStandard1);
            this.Controls.Add(this.imageListComboBox2);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label15);
            this.Controls.Add(this.pictureBox10);
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(462, 441);
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(462, 441);
            this.Name = "FormBolt";
            this.Text = "FormBolt";
            this.TopMost = true;
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox10)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.CheckBox ch_checkw1;
        private System.Windows.Forms.CheckBox ch_checkw3;
        private System.Windows.Forms.CheckBox ch_checkw2;
        private System.Windows.Forms.CheckBox ch_checkn1;
        private System.Windows.Forms.CheckBox ch_checkn2;
        private System.Windows.Forms.CheckBox ch_checkb;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.TextBox txt_Bolt_tole;
        private Tekla.Structures.Dialog.UIControls.BoltCatalogSize boltCatalogSize1;
        private System.Windows.Forms.TextBox txt_Bolt_extra;
        private Tekla.Structures.Dialog.UIControls.BoltCatalogStandard boltCatalogStandard1;
        private Tekla.Structures.Dialog.UIControls.ImageListComboBox imageListComboBox2;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.PictureBox pictureBox10;
        private System.Windows.Forms.ImageList imageList1;
    }
}